version: "3.8"

services:
  konnekt-session:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=debug,konnekt_session=debug,tower_http=debug
      - RUST_BACKTRACE=1
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_SERVICE_NAME=konnekt-session
      - WEBSOCKET_URL=ws://0.0.0.0:3000
      - ENABLE_TELEMETRY=true
    depends_on:
      jaeger:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # Jaeger compact thrift over compact thrift
      - "6832:6832/udp" # Jaeger compact thrift over binary thrift
      - "16686:16686" # Jaeger UI
      - "14250:14250" # Jaeger collector
      - "14268:14268"
      - "14269:14269"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 1s
      timeout: 3s
      retries: 3
      start_period: 5s
